### ISSUE TITLE
Generate Lineup?

### ISSUE THREAD

**Issue by kevinsoltis41** [squdgy/dailyfantasystatstool#2]
Have you ever thought of adding a 'generate lineup' feature based on the based available criteria?
Ie. If you already have a player selected; build best available lineup w/ available salary & positions?

**Comment by squdgy** [comment]
Yes. That is in the plans. I just have been more focused on other things, so not sure when I can get to that.

**Comment by kevinsoltis41** [comment]
Still couldn't run but thanks for your help.
Good luck on the generation; I've done it before and the best approach I figured out was a modification on the knapsack alg. - Thanks and Good luck
